//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POETraderWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POE_PROPERTY
    {
        public long ID { get; set; }
        public Nullable<long> ITEM_ID { get; set; }
        public Nullable<int> DISPLAY_MODE { get; set; }
        public Nullable<int> TYPE { get; set; }
        public Nullable<int> PROGRESS { get; set; }
        public Nullable<sbyte> IS_ADDITIONAL_PROPERTY { get; set; }
        public Nullable<int> PROPERTY_VALUE { get; set; }
        public Nullable<long> PROPERTY_TYPE_ID { get; set; }
        public string PROPERTY_VALUE_STRING { get; set; }
    
        public virtual POE_ITEM POE_ITEM { get; set; }
        public virtual POE_PROPERTY_TYPE POE_PROPERTY_TYPE { get; set; }
    }
}
