//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POETraderWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POE_ACCOUNT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POE_ACCOUNT()
        {
            this.POE_STASH = new HashSet<POE_STASH>();
        }
    
        public long ID { get; set; }
        public string ACCOUNT_NAME { get; set; }
        public string LAST_CHAR_NAME { get; set; }
        public Nullable<System.DateTime> LAST_ITEM_ADDED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POE_STASH> POE_STASH { get; set; }
    }
}
