//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POETraderWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POE_MODS
    {
        public long ID { get; set; }
        public Nullable<long> ITEM_ID { get; set; }
        public string MOD_TEXT { get; set; }
        public Nullable<sbyte> MOD_TYPE { get; set; }
    
        public virtual POE_ITEM POE_ITEM { get; set; }
    }
}
