//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POETraderWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class poe_traderEntities : DbContext
    {
        public poe_traderEntities()
            : base("name=poe_traderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<POE_ACCOUNT> POE_ACCOUNT { get; set; }
        public virtual DbSet<POE_CHANGE> POE_CHANGE { get; set; }
        public virtual DbSet<POE_ITEM> POE_ITEM { get; set; }
        public virtual DbSet<POE_MODS> POE_MODS { get; set; }
        public virtual DbSet<POE_PROPERTY> POE_PROPERTY { get; set; }
        public virtual DbSet<POE_PROPERTY_TYPE> POE_PROPERTY_TYPE { get; set; }
        public virtual DbSet<POE_REQUIREMENT> POE_REQUIREMENT { get; set; }
        public virtual DbSet<POE_REQUIREMENT_TYPE> POE_REQUIREMENT_TYPE { get; set; }
        public virtual DbSet<POE_SOCKET> POE_SOCKET { get; set; }
        public virtual DbSet<POE_STASH> POE_STASH { get; set; }
    }
}
