//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POETraderWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POE_CHANGE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POE_CHANGE()
        {
            this.POE_ITEM = new HashSet<POE_ITEM>();
        }
    
        public long ID { get; set; }
        public string NEXT_CHANGE_ID { get; set; }
        public Nullable<System.DateTime> CHANGE_RECEIVED { get; set; }
        public Nullable<int> STASH_COUNT { get; set; }
        public string JSON_DATA { get; set; }
        public Nullable<sbyte> PROCESSED { get; set; }
        public Nullable<sbyte> JSON_DATA_RETRIEVED { get; set; }
        public Nullable<System.DateTime> CHANGE_PROCESSED { get; set; }
        public Nullable<sbyte> IN_PROCESS { get; set; }
        public Nullable<System.DateTime> PROCESS_START { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POE_ITEM> POE_ITEM { get; set; }
    }
}
