//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POETraderWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POE_STASH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POE_STASH()
        {
            this.POE_ITEM = new HashSet<POE_ITEM>();
        }
    
        public long STASH_UNIQUE_ID { get; set; }
        public string ID { get; set; }
        public string STASH_NAME { get; set; }
        public string STASH_TYPE { get; set; }
        public Nullable<long> ACCOUNT_ID { get; set; }
    
        public virtual POE_ACCOUNT POE_ACCOUNT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POE_ITEM> POE_ITEM { get; set; }
    }
}
